### ISSUE TITLE
Token Transfer Feature

### ISSUE THREAD

**Issue by chrlschwb** [Joystream/discord-bot#2]
https://pioneerapp.xyz/#/forum/thread/316

The current discord bot already couples the discord ID to a certain membership. 
So this new feature requires to call the tokenSend extrinsic.

The parameters should be like this.
`/send discordId amount rationale privatekey`

**Comment by chrlschwb** [comment]
**Revised plan for the token transfer feature**

four commands:
`/deposit amount privatekey`  will transfer tokens from the user's membership account to a predefined Joystream account that will act as a pool for all discord users, and increase this user's "token" value in db.
`/tokens` will return the user's "token" value in db
`/send discordId amount` will decrease the sender's "token" value in db and increase the recipient's value by amount.
`/withdraw amount` will check if the user has an equal or larger value of "token" than "amount" and decrease the db value, while transfering tokens from the pool to the user's membership wallet.

**Comment by bedeho** [comment]
see this instead https://github.com/Joystream/discord-bot/issues/6
